name: Deployment

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clean output directory in repository
        run: rm ./dist/.gitkeep

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Generate site
        run: uv run html-elements-showcase

      - name: Upload output as artifact for GitHub pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: dist/

  deploy:
    needs: build
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
